spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          default_batch_fetch_size: 1000
          open-in-view: false
          show_sql: true
          format_sql: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            store_data_at_delete: true
            revision_field_name: revision_id
            revision_type_field_name: revision_type
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  profiles:
    include: >
      jwt, 
      scrap

feign:
  client:
    config:
      default:
        connectTimeout: 40000
        readTimeout: 40000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        waitDurationInOpenState: 50s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 25s
        registerHealthIndicator: true
        recordFailurePredicate: com.o3.openfeign.circuit.DefaultExceptionRecordFailurePredicate
    instances:
      default:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 30s
        cancelRunningFuture: true

logging:
  level:
    com.o3.openfeign: DEBUG
    org.springframework.jdbc.core: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

